import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import {
  NavigationMenu,
  NavigationMenuLink,
  NavigationMenuList,
} from '@/components/ui/navigation-menu'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
                                     children
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <NavigationMenu className="w-full max-w-4xl bg-white rounded-lg">
      <NavigationMenuList className="flex justify-around p-4">
        <Link href='/' legacyBehavior passHref>
          <NavigationMenuLink className="px-4 py-2 rounded hover:bg-gray-100 transition">Home</NavigationMenuLink>
        </Link>
        <Link href='/gallery' legacyBehavior passHref>
          <NavigationMenuLink className="px-4 py-2 rounded hover:bg-gray-100 transition">Gallery</NavigationMenuLink>
        </Link>
        <Link href='/map' legacyBehavior passHref>
          <NavigationMenuLink className="px-4 py-2 rounded hover:bg-gray-100 transition">Map</NavigationMenuLink>
        </Link>
        <Link href='/upload' legacyBehavior passHref>
          <NavigationMenuLink className="px-4 py-2 rounded hover:bg-gray-100 transition">Upload</NavigationMenuLink>
        </Link>
      </NavigationMenuList>
    </NavigationMenu>
    {children}
    </body>
    </html>
  )
}
